// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 4.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'widgets';

  static const String $______assets_3_Something_Went_Wrong_png = '../../assets/3_Something Went Wrong.png';
  static const String widgets$______assets_3_Something_Went_Wrong_png = 'packages/widgets/../../assets/3_Something Went Wrong.png';

  static const String $______assets_animations = '../../assets/animations';
  static const String widgets$______assets_animations = 'packages/widgets/../../assets/animations';

  static const String $______assets_logo_png = '../../assets/logo.png';
  static const String widgets$______assets_logo_png = 'packages/widgets/../../assets/logo.png';

  static const String $______assets_logo_transparent_png = '../../assets/logo_transparent.png';
  static const String widgets$______assets_logo_transparent_png = 'packages/widgets/../../assets/logo_transparent.png';
}
